update readme - new release ref in usage example
asos-craigmorten/opine pull request #166
Opened 2022-04-07 16:40 UTC by michael-spengler

2022-04-07 16:48 UTC, asos-craigmorten commented
Ah good spot - would also need to update the values in the "Installation" section as these still point to `2.1.4`.

Looks like the formatted has gone a lil awry - _think_ was using `deno fmt` before to help guide this (but could well be my vscode plugin setup). Would be good to keep the formatting of TS snippets consistent.

2022-04-07 17:03 UTC, michael-spengler commented
@asos-craigmorten: 
you're right I'm e.g. always getting rid of semicolons at the end of lines as they come from a time where people wrote several statements in one line (which is dinosaur style imo :) ) 

I'll take better care of consistent formatting next time applying your https://github.com/cmorten/opine/blob/main/.vscode/settings.json settings ... 

P.S. 
opine is awesome - I'm using it for my lectures for the off-chain backend parts --> also my students like it a lot.
https://github.com/michael-spengler/distributed-ledger-technology-hands-on-lecture ...

2022-04-08 10:19 UTC, asos-craigmorten requested changes

2022-04-08 10:19 UTC, asos-craigmorten commented on README.md
>  ## Installation
As discussed version changes needed in the installation section as well.

2022-05-02 13:30 UTC, cmorten commented
Superseded by https://github.com/cmorten/opine/pull/167

2022-05-02 13:30 UTC, closed without merging